aliases:
  - &android
    components:
      - build-tools-28.0.3
      - android-29
      - extra-android-m2repository
      - extra-android-support
  
  - &android-cache
    directories:
      - ~/.npm
      - ~/.gradle/caches/modules-2
      - ~/.gradle/wrapper
  
  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods

  - &init-new-project
    |
      nvm install node
      yarn global add react-native-cli
      react-native init App --version="0.58.4"
      cd App
      yarn add react-native-amap-geolocation@next

jobs:
  include:
    - stage: "build test for example"
      language: android
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - nvm install node
        - npm i && npm i typescript
        - npm run build
        - cd android && TERM=dumb ./gradlew build
        - ls -lh app/build/outputs/apk/debug
        - ls -lh app/build/outputs/apk/release

    - stage: "build test for example"
      language: objective-c
      os: osx
      osx_image: xcode11.5
      cache: *ios-cache
      script:
        - npm i && npm i typescript
        - npm run build
        - cd ios && pod install && cd ..
        - npm run run-ios > /dev/null

    - stage: "build test for new project"
      language: android
      jdk: oraclejdk8
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - *init-new-project
        - react-native link
        - cd android
        - ./gradlew build
        - ls -lh app/build/outputs/apk

    - stage: "build test for new project"
      language: objective-c
      osx_image: xcode10.1
      cache: *ios-cache
      script:
        - brew install yarn
        - *init-new-project
        - cd ios
        - pod install
        - xcodebuild -workspace App.xcworkspace -scheme App -sdk iphonesimulator -quiet

stages:
  - name: "build test for example"
    if: branch = master
  - name: "build test for new project"
    if: branch = release
